### ISSUE TITLE
when i use docker to install it , i can't find the image

### ISSUE THREAD

**Issue by bringtree** [TykTechnologies/tyk-pump-docker-pub#2]
Error response from daemon: repository tykio/tyk-pump not found: does not exist or no pull access

**Comment by mvdan** [comment]
Perhaps you're using the wrong Docker registry? Can you reproduce this on a machine with a vanilla Docker setup, i.e. no changed settings?

/cc @buger

**Comment by bringtree** [comment]
oh .. i know why ....
https://store.docker.com/community/images/tykio/tyk-pump-docker-pub

in the Quickstart saies 
```
Get Tyk Pump

docker pull tykio/tyk-pump
```

but  the truth is` docker pull tykio/tyk-pump-docker-pub`
