### ISSUE TITLE
Docker Version Tags

### ISSUE THREAD

**Issue by senj** [TykTechnologies/tyk-pump-docker-pub#5]
I noticed there was a new docker build 12 days ago with the latest tag and 51mb.
The latest versioned tag is v0.5.1 three months ago with 50mb.

Has anything changed? Will there be a 0.5.2 soon?

**Comment by excieve** [comment]
@buger Could you please tag 0.5.2 when you've got a moment?

**Comment by ch0wnag3** [comment]
Hi, guys.

Any chance the same thing could be done for v0.5.3, please?

Thanks in advance!

**Comment by Neirda24** [comment]
@buger : Any news for the `v0.5.3` on docker ?

**Comment by a-nldisr** [comment]
Can be closed, right?

**Comment by buger** [comment]
yes :)
